# Generated by Django 2.2.5 on 2020-02-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('category_tag', models.CharField(max_length=30)),
                ('hdd', models.IntegerField(null=True)),
                ('ssd', models.IntegerField()),
                ('resolution', models.CharField(choices=[('SD', '640x480'), ('HD', '1280x720'), ('FHD', '1920x1080'), ('4K UHD', '3840x2160'), ('8K UHD', '7680x4320')], max_length=6)),
                ('display', models.IntegerField(choices=[(13, '(32~34)cm'), (14, '(35~36)cm'), (15, '(37~39)cm'), (16, '(40~42)cm'), (17, '(43~44)cm')])),
                ('price', models.IntegerField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp_api.Cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fp_api.Gpu')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('min_gpuram', models.IntegerField(null=True)),
                ('min_ram', models.IntegerField()),
                ('min_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp_api.Cpu')),
                ('min_gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp_api.Gpu')),
            ],
        ),
    ]
