# Generated by Django 2.2.5 on 2020-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ['point']},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'ordering': ['point']},
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
