# Generated by Django 2.2.5 on 2020-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0002_auto_20200210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='point',
            field=models.FloatField(),
        ),
    ]
