# Generated by Django 2.2.5 on 2020-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0003_auto_20200210_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
