# Generated by Django 2.2.5 on 2020-02-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0004_auto_20200211_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(max_length=15),
        ),
    ]
