# Generated by Django 2.2.5 on 2020-02-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0008_auto_20200212_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(),
        ),
    ]
