# Generated by Django 2.2.5 on 2020-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0009_auto_20200212_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.FloatField(),
        ),
    ]
