# Generated by Django 2.2.5 on 2020-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0010_auto_20200212_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='hdd',
            field=models.FloatField(null=True),
        ),
    ]
