# Generated by Django 2.2.5 on 2020-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_api', '0011_auto_20200212_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.IntegerField(choices=[(13, '13인치 (32~34)cm'), (14, '14인치 (35~36)cm'), (15, '15인치 (37~39)cm'), (16, '16인치 (40~42)cm'), (17, '17인치 (43~44)cm')], null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
